development:
  adapter: postgresql
  encoding: unicode
  database: movie_app_db
  pool: 2
  username: movie_app_user
  password: movie_app_password
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
